export function createNodePreset({ js, eslintConfigPrettier, unicorn, globals, tseslint, base }) {
    return tseslint.config(
        {
            ignores: [
                'dist/**',
                'bin/**',
                'app/gen/**',
                'node_modules/**',
                '.prettierrc.cjs',
                'prettier.config.mjs',
                'plugins/**',
                'scripts/**',
            ],
        },
        js.configs.recommended,
        ...tseslint.configs.recommended,
        { plugins: { unicorn }, rules: unicorn.configs.recommended.rules },
        base,
        {
            languageOptions: {
                globals: {
                    ...globals.node,
                },
            },
            rules: {
                semi: 'off',
                indent: 'off',
                'linebreak-style': ['error', 'unix'],
                'valid-jsdoc': 'off',
                'comma-dangle': 'off',
                'object-curly-spacing': 'off',
                camelcase: 'off',
                'no-unused-vars': 'off',
                '@typescript-eslint/no-unused-vars': 'error',
                'import/no-unresolved': 'off',
                'import/named': 'off',
                'import/extensions': 'off',
                'unicorn/no-array-reduce': 'off',
                'no-prototype-builtins': 'off',
                'unicorn/no-useless-undefined': 'off',
                'operator-linebreak': 'off',
                'unicorn/filename-case': 'off',
                'no-param-reassign': ['error', { props: false }],
                'no-nested-ternary': 'warn',
                'consistent-return': 'off',
                'no-shadow': 'off',
                '@typescript-eslint/no-shadow': 'warn',
                'no-restricted-exports': 'off',
                'import/no-cycle': 'off',
                'import/no-named-as-default': 'off',
                'import/prefer-default-export': 'off',
                'unicorn/prevent-abbreviations': 'off',
                'unicorn/no-null': 'off',
                'unicorn/prefer-module': 'off',
                'unicorn/import-style': 'off',
                'unicorn/no-process-exit': 'off',
                'unicorn/consistent-destructuring': 'off',
                'unicorn/no-array-callback-reference': 'off',
                'unicorn/name-replacements': 'off',
                'unicorn/text-encoding-identifier-case': 'off',
                'unicorn/no-useless-switch-case': 'off',
                'unicorn/prefer-await': 'off',
                'unicorn/prefer-top-level-await': 'off',
                'unicorn/class-reference-in-static-methods': 'off',
                'unicorn/consistent-class-member-order': 'off',
                'unicorn/no-break-in-nested-loop': 'off',
                'unicorn/no-unnecessary-splice': 'off',
                'unicorn/prefer-iterator-to-array': 'off',
                'unicorn/no-array-sort': 'off',
                'unicorn/require-array-sort-compare': 'off',
                'unicorn/prefer-spread': 'off',
                'unicorn/prefer-structured-clone': 'off',
                'unicorn/prefer-object-iterable-methods': 'off',
                'unicorn/no-array-reverse': 'off',
                'unicorn/no-top-level-assignment-in-function': 'off',
                'unicorn/consistent-boolean-name': 'off',
                'unicorn/no-computed-property-existence-check': 'off',
                'no-underscore-dangle': ['error', { allow: ['__dirname', '__filename'] }],
                '@typescript-eslint/no-explicit-any': 'off',
                '@typescript-eslint/ban-ts-comment': 'off',
                '@typescript-eslint/no-non-null-assertion': 'warn',
                'class-methods-use-this': 'off',
                'no-restricted-syntax': 'off',
                'no-continue': 'off',
                'no-await-in-loop': 'off',
                'no-empty': 'off',
                'no-console': 'warn',
                'no-use-before-define': 'off',
            },
        },
        {
            files: ['libs/eslint/**/*.mjs', 'eslint.config.js'],
            rules: {
                'import/no-extraneous-dependencies': 'off',
            },
        },
        {
            files: ['*.config.ts', 'typescript-openapi-generator.ts', 'tests/**/*.ts'],
            rules: {
                'import/no-extraneous-dependencies': 'off',
                'import/extensions': 'off',
            },
        },
        eslintConfigPrettier,
    );
}
